direction: right
root: track-monorepo
root.shape: page

root.cmd.shape: package
root.cmd.tmp: template
root.cmd.tmp.shape: package
root.cmd.acc: account
root.cmd.acc.shape: package

root.gateway.shape: package

root.pkg.shape: package

root.dfile: Dockerfile
root.dfile: {
  icon: https://icons.terrastruct.com/essentials%2F257-file.svg
}
root.gmod: go.mod
root.gmod: {
  icon: https://icons.terrastruct.com/essentials%2F257-file.svg
}
root.gsum: go.sum
root.gsum: {
  icon: https://icons.terrastruct.com/essentials%2F257-file.svg
}

root.mfile: Makefile
root.mfile: {
  icon: https://icons.terrastruct.com/essentials%2F257-file.svg
}